### ISSUE TITLE
Socket as reference when closing

### ISSUE THREAD

**Issue by fouge** [rust-embedded-community/embedded-nal#38]
Hello,
I was wondering if there wasn't an error when closing the socket

Shouldn't the signature be:

```rust
	fn close(&self, socket: &Self::TcpSocket) -> Result<(), Self::Error>;
```

Instead of:

```rust
	fn close(&self, socket: Self::TcpSocket) -> Result<(), Self::Error>;
```

So that it can take the reference of the socket.

Best,
Cyril

**Comment by ryan-summers** [comment]
The intent is that the socket is no longer usable once it has been closed, which is why the close function is intended to take ownership of the socket again. The idea is that you are given a socket in `socket()` and you are returning the socket when you call `close()`.

However, I don't think we really considered potential errors when closing the socket. We likely need to update the return signature here to return the socket + error if the `close()` fails.

**Comment by fouge** [comment]
Hey @ryan-summers 

I have to say I am a bit confused as my compiler doesn't accept to move the value. Rust can be really frustrating sometimes... 

The only choice I have left looks like I need to `mem::replace` the value somehow...
https://doc.rust-lang.org/error-index.html#E0507

:thinking:

**Comment by caemor** [comment]
The 507 error tells you that there should be an open borrow of your socket somewhere most likely. Do you have a code snippet (or the full repo) where the error is happening?

**Comment by fouge** [comment]
Here is a snippet:

```rust
pub struct Rpc<'a, S> {
	socket: S,
	ws: ws::WebSocketClient<SmallRng>,
	in_buf: [u8; 4096],
	out_buf: [u8; 4096],
	tcp: &'a dyn TcpClientStack<TcpSocket=S, Error=TcpError>,
	cmd_id: usize,
}
```

```rust
	pub fn disconnect(&mut self) -> Result<(), RpcError> {
		// initiate a close handshake
		let send_size = self.ws.close(WebSocketCloseStatusCode::NormalClosure, None, &mut self.out_buf)?;
		self.tcp.send(&mut self.socket, &self.out_buf[..send_size])?;

		// read the reply from the server to complete the close handshake
		let received_size = self.tcp.receive(&mut self.socket, &mut self.in_buf)?;
		let ws_result = self.ws.read(&self.in_buf[..received_size], &mut self.out_buf)?;
		match ws_result.message_type {
			WebSocketReceiveMessageType::CloseCompleted => {
				// we can close the TCP socket as well
				self.tcp.close(self.socket)?;
				Ok(())
			}
			_ => {
				Err(RpcError::ErrorClosing)
			}
		}
	}
```

**Comment by ryan-summers** [comment]
You can't have the socket be a member of your structure, since the structure **always** owns it and it's not possible to move. Instead, you should store your `socket` as an `Option<S>` and move it in/out of the `Option` when you open/close it.

Logically, your structure can't own a socket that does not yet exist. Similarly, it can not give away a socket that it never created. You have to account for this in your code through `Option`s or other methods.

Your `disconnect()` method should have something along the lines of:

```rust
// Construct your socket.
let socket = self.tcp.socket();
self.socket.replace(socket);

// Release your socket.
let socket = self.socket.take().and_then(|socket| self.tcp.close(socket));
```

**Comment by fouge** [comment]
Thank you guys!
It's kind of obvious that my structure shouldn't store something that can be destroyed... :thinking: 

It works now. :pray: 
Cyril
