### ISSUE TITLE
Async/Await

### ISSUE THREAD

**Issue by olanod** [rust-embedded-community/embedded-nal#6]
Perhaps worth designing those APIs to be async/await friendly from the beginning? Soon everything in the Rust world will be asynchronous and embedded [won't be the exception](https://ferrous-systems.com/blog/async-on-embedded/).

**Comment by thejpster** [comment]
Yes, I'm very aware of what Ferrous have been up to. Would you like to propose an API?

**Comment by ryan-summers** [comment]
Just to add some bit to the discussion - I don't think it's safe to ever say:

> Soon everything in the Rust world will be asynchronous and embedded won't be the exception.

I disagree. The article you link talks about this as well - async is really nice for cooperative multitasking, but it does _not_ work well for hard real-time systems (e.g. safety critical) because there's no guarantee when other tasks will release their execution. There's always exceptions and specific use cases in software.

I definitely support adding async/await traits, but I don't think they should be the only possible API. Perhaps we can have an `AsyncTcpStack` as well as an `AsyncUdpStack` added that use async read/write functions. Then, drivers that make use of async/await can request the associated async stack.

**Comment by chrysn** [comment]
It should be noted in this issue that there is now an experimental crate [embedded-nal-async](https://crates.io/crates/embedded-nal-async) that is [being developed as part of this repository](https://github.com/rust-embedded-community/embedded-nal/tree/master/embedded-nal-async).

[edit: All my links and names had a line above the `n` of `nal` and accidentally looked like `hal` ... but the statement holds]

**Comment by ryan-summers** [comment]
In light of that, I'm going to close this issue as resolved - thanks for noting this @chrysn! I had neglected to back-trace through issues after approving the async NAL.

We would welcome any further contributions to the async stack!
